# Generated by Django 3.2.9 on 2021-11-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211114_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='total_score',
            new_name='total_rating',
        ),
    ]
