# Generated by Django 3.2.9 on 2021-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
